# Generated by Django 2.0.7 on 2019-07-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pruduct',
            new_name='Products',
        ),
    ]
